name: Deploy Next CI

on:
  pull_request:

env:
  AZURE_WEBAPP_NAME: mwolab
  AZURE_WEBAPP_PACKAGE_PATH: "./mwo"
  NODE_VERSION: "18.x"

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        working-directory: mwo
        run: npm ci
      - name: Build
        working-directory: mwo
        run: npm run build
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
